### ISSUE TITLE
Use with TypeScript!?

### ISSUE THREAD

**Issue by kristianmandrup** [overlookmotel/fs-extra-promise#16]
I can't seem to figure out how to use this library with TypeScript (and async/await) .
I'm told either that it returns void or that it returns a promise which then seems to resolve to void when I await for it. Please advice.

``` js
import { readJson, readJsonSync } from 'fs-extra-promise';

  // sync
  loadPackage() : Object {
    try {
      return readJsonSync(this.path);
    } catch (err) {      
    }  
  }
```

Trying with `async`:

``` js
  async loadPackage() : Promise<Object> {
    try {
      return readJson(this.path);
    } catch (err) {
      return {};      
    }  
  }
```

Also tried `return readJson(this.path).then(obj => return obj);` to no avail.

**Comment by overlookmotel** [comment]
I have no idea about Typescript - never used it - so I'm not 100% sure how to read your code examples above. In an async function, don't you need to `await` the response rather than `return` it?

But... the promise-returning methods have 'Async' on the ends of their names. So in your examples above, I think the method you should be using is `fs.readJsonAsync()`.

So, `readJsonAsync(this.path).then(obj => return obj);`

Let me know if that solves your problem.

NB This module is just a thin wrapper around [fs-extra](https://www.npmjs.com/package/fs-extra). It's also worth checking the non-promisified version of the function and see if that works. If not, the problem is probably in [fs-extra](https://www.npmjs.com/package/fs-extra) rather than this module.

**Comment by kristianmandrup** [comment]
Sweet, I thought `readJson` was async and returned a promise. I didn't notice there was a specific `readJsonAsync` variant. I will try it out ASAP. Thanks!
Perhaps improve the docs for async/await and also on how to use/install the typings for TypeScript

`typings install dt~fx-extra-promise --global --save`

Cheers!
